Constants = {
  "ACCESS_TOKEN_SECRET": "canhtuan97",
  "ACCESS_TOKEN_LIFE_RESET_PASSWORD": "3h",
  "REFRESH_TOKEN_SECRET": "sad",
  "REFRESH_TOKEN_LIFE": "10",
  "HouseHolds": "3",
  "LienGorup": "1",
  "Group": "2",
  "LenghDat": "4",
  "LenghNuoc": "4",
  "LenghGiong": "3",
  "LenghInfo": "3",
  "VietGap": [{
    "sku": "InfoProduct",
    "name": "Thông tin sản phẩm",
    "contract": [
      { "sku": "time", "name": "Thời gian" },
      { "sku": "name", "name": "Tên" },
      { "sku": "dia_diem", "name": "Địa điểm" },
      { "sku": "dien_tich", "name": "Diện tích(km2)" },
    ],
      "status": 2,
    },
    {
      "sku": "History",
      "name": "Lịch sử",
      "contract": [
        { "sku": "time", "name": "Thời gian" },
        { "sku": "action", "name": "Hành động" },
        { "sku": "key", "name": "code" },
        { "sku": "description", "name": "Miêu tả" },
      ],
      "status": 1,
    },
    {
      "sku": "Dat",
      "name": "Thông tin về đất",
      "contract": [
        { "sku": "time", "name": "Thời gian" },
        { "sku": "loai_dat", "name": "Loại đất" },
        { "sku": "ph", "name": "Độ Ph" },
        { "sku": "vi_tri", "name": "Vị trí" },
        { "sku": "description", "name": "Miêu tả" },
      ],
      "status": 2,
    },
    {
      "sku": "Nuoc",
      "name": "Thông tin nguồn nước",
      "contract": [
        { "sku": "time", "name": "Thời gian" },
        { "sku": "nguon_nuoc", "name": "Nguồn nước" },
        { "sku": "ph", "name": "Độ Ph" },
        { "sku": "vi_tri", "name": "Vị trí" },
        { "sku": "description", "name": "Miêu tả" },
      ],
      "status": 2,
    },
    {
      "sku": "Giong",
      "name": "Thông tin giống cây",
      "contract": [
        { "sku": "time", "name": "Thời gian" },
        { "sku": "ten_giong", "name": "Tên giống" },
        { "sku": "nguon_goc", "name": "Nguồn gốc" },
        { "sku": "vi_tri", "name": "Vị trí" },
        { "sku": "description", "name": "Miêu tả" },
      ],
      "status": 2,
    },
    {
      "sku": "QrCode",
      "name": "Thông tin key Qr code",
      "contract": [
        { "sku": "time", "name": "Thời gian" },
        { "sku": "action_name", "name": "Hành động" },
        { "sku": "description", "name": "Miêu tả" },
      ],
      "status": 1,
    },
  ],
}